version: '2.1'
services: 
        inference:
                build: ./inference
                privileged: true
                restart: always
                network_mode: host
                container_name: inference
                cap_add:
                        - CAP_SYS_ADMIN
                        - CAP_SYS_RAWIO
                ports: 
                        - "80:80"
                        - "4912:4912"
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                environment:
                        UDEV: 1
                        PULSE_SERVER: tcp:audio:4317
                devices:
                        - '/dev:/dev'
         audio:
                image: balenablocks/audio
                privileged: true
                ports:
                        - 4317:4317
        
volumes:
        shared-data:
        shared-media:
